### ISSUE TITLE
GraphiQL crashes after adding a plugin

### ISSUE THREAD

**Issue by michal-wajrak** [mercurius-js/mercurius#1103]
Adding a plugin to GraphiQL (in my case @graphiql/plugin-explorer), causes the /graphiql endpoint to crash.

**Error shown in the console**:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'umdPlugin')
    at main.js:145:78
    at Array.map (<anonymous>)
    at render (main.js:145:36)`

**index.ts:**
`const app = Fastify({
	logger: true,
});

const prisma = new PrismaClient();

app.register(mercurius, {
	schema,
	resolvers,
	context: () => {
		return { prisma };
	},
	graphiql: {
		enabled: true,
		plugins: [
			{
				name: "explorerPlugin",
				umdUrl: "https://unpkg.com/@graphiql/plugin-explorer/dist/index.umd.js",
			},
		],
	},
});
`

**Dependencies**:
"mercurius": "14.1.0"
"fastify": "4.28.1",
"node": "20.13.1"

![mercurius-graphiql-plugin-issue](https://github.com/user-attachments/assets/dbf35407-7c28-425a-9d5b-a8e9318d8da4)

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
