### ISSUE TITLE
Instanceof not working in errorFormatter

### ISSUE THREAD

**Issue by WKampel** [mercurius-js/mercurius#1106]
I'm throwing this customer error in my resolver:

```
import { ApplicationError } from './application.error'

type FieldError = {
  field: string
  message: string
}

export class FieldValidationError extends ApplicationError {
  public fieldErrors: FieldError[]

  constructor(fieldErrors: FieldError | FieldError[], message?: string) {
    if (!message) message = `Validation failed for field${Array.isArray(fieldErrors) && fieldErrors.length > 1 ? 's' : ''}`

    super(message)

    this.fieldErrors = Array.isArray(fieldErrors) ? fieldErrors : [fieldErrors]
  }
}
```

The errorFormatter is supposed to catch it and convert it to a graphql error. However, testing the instanceof returns false. I added logs for more details.

```
import { FastifyInstance } from 'fastify'
import { readFileSync } from 'fs'
import mercurius from 'mercurius'
import { join } from 'path'
import { loadResolvers } from '../../graphql/loadResolvers'
import { ApplicationError } from '../../modules/core/errors/application.error'
import { FieldValidationError } from '../../modules/core/errors/field-validation.error'

export function setupGraphQL(server: FastifyInstance) {
  const schema = readFileSync(join(process.cwd(), 'src/graphql/schema.gql'), 'utf8')

  server.register(mercurius, {
    schema,
    resolvers: loadResolvers(),
    errorFormatter: result => {
      const originalError = result.errors[0]?.originalError

      if (originalError instanceof FieldValidationError) {
        console.log('Success')
      } else {
        console.log('Failed. the instance is:', originalError)
        console.log('Type of originalError:', typeof originalError)
        console.log('Constructor of originalError:', originalError?.constructor.name)
      }

      if (originalError instanceof FieldValidationError) {
        return {
          statusCode: 400,
          response: {
            message: originalError.message,
            extensions: {
              fieldErrors: originalError.fieldErrors,
            },
          },
        }
      }

      if (originalError instanceof ApplicationError) {
        return {
          statusCode: 400,
          response: { message: originalError.message },
        }
      }

      return {
        statusCode: 500,
        response: {
          message: 'Internal Server Error',
        },
      }
    },
  })
}
```

This is what logs:

```
Failed. the instance is: FieldValidationError: Validation failed for fields
    at validateInput (/app/dist/src/modules/core/utils/validate-input.js:12:15)
    at registerPracticeUseCase (/app/dist/src/modules/practice/register-practice/register-practice.use-case.js:23:132)
    at registerPractice (/app/dist/src/modules/practice/register-practice/register-practice.resolver.js:7:83)
    at executeField (/app/node_modules/graphql/execution/execute.js:492:20)
    at /app/node_modules/graphql/execution/execute.js:377:22
    at promiseReduce (/app/node_modules/graphql/jsutils/promiseReduce.js:23:9)
    at executeFieldsSerially (/app/node_modules/graphql/execution/execute.js:373:43)
    at executeOperation (/app/node_modules/graphql/execution/execute.js:347:14)
    at execute (/app/node_modules/graphql/execution/execute.js:136:20)
    at Object.fastifyGraphQl [as graphql] (/app/node_modules/mercurius/index.js:552:29) {
  fieldErrors: [
    { field: 'email', message: 'Invalid email format' },
    { field: 'firstName', message: 'First name is required' },
    { field: 'practiceName', message: 'Practice name is required' },
    { field: 'practiceSlogan', message: 'Practice slogan is required' },
    {
      field: 'practiceUrl',
      message: 'Practice identifier is required'
    },
    {
      field: 'practiceUrl',
      message: 'Practice identifier can only contain letters and numbers'
    }
  ]
}
Type of originalError: object
Constructor of originalError: FieldValidationError

```

**Comment by WKampel** [comment]
Solved. This was unrelated to mercurius.

I was dynamically loading resolvers in the dist/ folder, so the instanceof was wrong with my development in typescript.
