### ISSUE TITLE
Jest - Fastify v5 - Mercurius@15.1.0  - error in tests from `buildCache`

### ISSUE THREAD

**Issue by javierxbrenes1** [mercurius-js/mercurius#1122]
Hey, we have tried to update our BE app to start using Fastify v5, we had to update to Mercurius@15.1.0, but now when we want to run our tests -we use jest- we are getting the following error: 

```
  TypeError: A dynamic import callback was invoked without --experimental-vm-modules

      at buildCache (../node_modules/mercurius/index.js:65:20)
      at Object.<anonymous>.fp.name (../node_modules/mercurius/index.js:71:21)
      at Plugin.Object.<anonymous>.Plugin.exec (../node_modules/avvio/lib/plugin.js:125:28)
      at Boot.Object.<anonymous>.Boot._loadPlugin (../node_modules/avvio/boot.js:432:10)
```

Seems buildCache does something like `const QuickLRU = (await import('quick-lru')).default` we know Nodejs supports this, but seems that Jest doesn't like it.

 is there any way to deal with this ?

**Comment by mcollina** [comment]
@voxpelli introduced the dependency on quick-lru in https://github.com/mercurius-js/mercurius/pull/1108. Maybe there is another LRU implementation that we can use that is not an ESM.

Anyhow, I recommend to not use jest, mostly for these kind of issues.

**Comment by voxpelli** [comment]
Yikes, Jest doesn’t support dynamic import of ESM modules?!

One can surely find or make an LRU implementation that behaves like a `Map` and isn’t an ESM module, but even if one does there is no guarantee that no other dependency of Mercurius suddenly starts using dynamic imports of ESM in their CJS – because that is perfectly fine and not a breaking change to do.

I would say that Jest is the one in the wrong here.

**Comment by voxpelli** [comment]
@javierxbrenes1 Have you tried running the tests with `--experimental-vm-modules`?

**Comment by mcollina** [comment]
I think the problem is in Jest and your setup, not here. This is perfectly valid code.
