### ISSUE TITLE
Error: subscription with redis

### ISSUE THREAD

**Issue by vnStrawHat** [mercurius-js/mercurius#382]
I try to implement graphql subscription using Fastify and mercurius follow this example (https://github.com/mercurius-js/mercurius/blob/master/docs/subscriptions.md#subscription-support-with-redis) but have error:
```
[nodemon] starting `babel-node src/index.js`
assert.js:386
    throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(message)

    at MQEmitterRedis.emit (/home/trungkfc/new-sub/node_modules/mqemitter/mqemitter.js:84:3)
    at handler (/home/trungkfc/new-sub/node_modules/mqemitter-redis/mqemitter-redis.js:48:12)
    at Redis.<anonymous> (/home/trungkfc/new-sub/node_modules/mqemitter-redis/mqemitter-redis.js:54:5)
    at Redis.emit (events.js:314:20)
    at Redis.EventEmitter.emit (domain.js:483:12)
    at DataHandler.handleSubscriberReply (/home/trungkfc/new-sub/node_modules/ioredis/built/DataHandler.js:82:28)
    at DataHandler.returnReply (/home/trungkfc/new-sub/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/home/trungkfc/new-sub/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/home/trungkfc/new-sub/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/home/trungkfc/new-sub/node_modules/ioredis/built/DataHandler.js:25:20) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

```
when start, app run successfully but when publish a message to channel NOTIFICATION, application crash with error above.
Here is my code:
```
'use strict'
const Fastify = require('fastify')
const mercurius = require('mercurius')
const app = Fastify()
const redis = require('mqemitter-redis')
const emitter = redis({
  port: 6379,
  host: '127.0.0.1'
})

const schema = `
  type Query {
    votes: [String]
  }


  type Subscription {
    notification: String
  }
`
const votes = []

const resolvers = {
  Query: {
    votes: async () => votes
  },
  Subscription: {
    notification: {
      subscribe: async (root, args, { pubsub }) => {
        return await pubsub.subscribe('NOTIFICATION')
      }
    }
  }
}

app.register(mercurius, {
  schema,
  resolvers,
  graphiql: 'playground',
  subscription: {
    emitter,
  }
})

app.listen(3000)
```
package.json:
```
{
  "name": "new-sub",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon --exec babel-node src/index.js"
  },
  "author": "TrungKFC",
  "license": "ISC",
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "dotenv": "^8.2.0",
    "fastify": "^3.10.1",
    "graphql-redis-subscriptions": "^2.3.1",
    "graphql-tools": "^7.0.2",
    "ioredis-eventemitter": "^1.0.1",
    "mercurius": "^6.10.0",
    "mqemitter-redis": "^4.0.3",
    "redis-emitter": "0.0.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/node": "^7.0.0",
    "@babel/plugin-transform-async-to-generator": "^7.1.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "nodemon": "^1.18.5"
  }
}
```
Reproduce:
- npm start
- redis-cli -h 127.0.0.1 -p 6379 PUBLISH NOTIFICATION AAA

Anyone know why this error happened and how to fix this ? Thanks so much.
Sorry for my bad English.

**Comment by mcollina** [comment]
You should publish using the internal API and not use the redis cli.

**Comment by vnStrawHat** [comment]
Thanks @mcollina for your response,

In my case, other application will publish data and this application will only subscribe data. How can I make it work like this ?

**Comment by mcollina** [comment]
You should use https://github.com/mcollina/mqemitter-redis and provide them in the required format (msgpack).
