### ISSUE TITLE
Question: Multiple GraphQL/Mercurius instances

### ISSUE THREAD

**Issue by Bas950** [mercurius-js/mercurius#569]
Right now I have this for a public API:
```
	app.register(mercurius, {
		schema: new GraphQLSchema({ query: RootQuery }),
		errorFormatter: (a, b) => {
			return {
				statusCode: (a as any).statusCode || 400,
				response: {
					data: a.data,
					errors: a.errors
				}
			};
		}
	});
```

But I also need a private API, "/graphql-private", but if I just register it again, it says:
`FastifyError: The decorator 'graphql' has already been added!`
Is there anyway to have multiple Mercurius instances?

**Comment by ansavchenco** [comment]
Is't possible to register hooks in child contexts? Docs say:
> When registering hooks, you must wait for Mercurius to be registered in Fastify.
> `await fastify.ready()`
When I add this line in a child context (not top level) I receive a timeout error.

**Comment by mcollina** [comment]
Can you include a full example to reproduce?

**Comment by ansavchenco** [comment]
Sure! I was able to reproduce it with the following.

```json
"dependencies": {
  "fastify": "3.19.1",
  "mercurius": "8.0.0"
}
```

```js
const fastify = require("fastify");
const mercurius = require("mercurius");

const schema = `
  type Query {
    add(x: Int, y: Int): Int
  }
`;

const resolvers = {
  Query: {
    add: async (_, { x, y }) => x + y,
  },
};

(async () => {
  const app = fastify();

  app.register(async (childContext) => {
    childContext.register(mercurius, { schema, resolvers });

    childContext.get("/", async function (req, reply) {
      const query = "{ add(x: 2, y: 2) }";
      return reply.graphql(query);
    });

    await childContext.ready();

    childContext.graphql.addHook("preParsing", (_schema, source) => {
      console.log(`Request body: ${source}`);
    });
  });

  await app.listen(3333, "localhost");
  console.log("Listening...");
})();
```
It results in this.
```
(node:44660) UnhandledPromiseRejectionWarning: Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: async (childContext) => { -- childContext.register(mercurius, { schema, resolvers });. You may have forgotten to call 'done' function or to resolve a Promise
    at Timeout._onTimeout (/Users/antonsavcenko/Development/mercurius-hook-problem/node_modules/avvio/plugin.js:123:19)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mcollina** [comment]
You should just remove ` await childContext.ready();`

```js
const fastify = require("fastify");
const mercurius = require("mercurius");

const schema = `
  type Query {
    add(x: Int, y: Int): Int
  }
`;

const resolvers = {
  Query: {
    add: async (_, { x, y }) => x + y,
  },
};

(async () => {
  const app = fastify();

  app.register(async (childContext) => {
    childContext.register(mercurius, { schema, resolvers });

    childContext.get("/", async function (req, reply) {
      const query = "{ add(x: 2, y: 2) }";
      return reply.graphql(query);
    });

    childContext.graphql.addHook("preParsing", (_schema, source) => {
      console.log(`Request body: ${source}`);
    });
  });

  await app.listen(3333, "localhost");
  console.log("Listening...");
})();
```

**Comment by ansavchenco** [comment]
Then `graphql` on `childContext` is `undefined`.

```
(node:49221) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addHook' of undefined
    at /Users/antonsavcenko/Development/mercurius-hook-problem/src/does-not-work.js:27:26
```

**Comment by mcollina** [comment]
```js

const fastify = require("fastify");
const mercurius = require("mercurius");

const schema = `
  type Query {
    add(x: Int, y: Int): Int
  }
`;

const resolvers = {
  Query: {
    add: async (_, { x, y }) => x + y,
  },
};

(async () => {
  const app = fastify();

  app.register(async (childContext) => {
    await childContext.register(mercurius, { schema, resolvers });

    childContext.get("/", async function (req, reply) {
      const query = "{ add(x: 2, y: 2) }";
      return reply.graphql(query);
    });

    childContext.graphql.addHook("preParsing", (_schema, source) => {
      console.log(`Request body: ${source}`);
    });
  });

  await app.listen(3333, "localhost");
  console.log("Listening...");
})();
```

**Comment by ansavchenco** [comment]
Yeah, this one works. Thanks a lot!
