### ISSUE TITLE
Specifying the schema object causes error & crash when using federationMetadata: true

### ISSUE THREAD

**Issue by destumme** [mercurius-js/mercurius#580]
Minimal example repository recreating bug: https://github.com/destumme/fastify-sample/tree/example/mercurius-schema-object-bug

When the schema object is present in the schema definition and federationMetadata is turned on the service fails to start with the following error message:

```
(node:82178) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at getStubTypes (/Users/danielstumme/code/personal/fastify-sample/node_modules/mercurius/lib/federation.js:95:38)
    at buildFederationSchema (/Users/danielstumme/code/personal/fastify-sample/node_modules/mercurius/lib/federation.js:273:50)
    at fp.name (/Users/danielstumme/code/personal/fastify-sample/node_modules/mercurius/index.js:155:16)
    at Plugin.exec (/Users/danielstumme/code/personal/fastify-sample/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/Users/danielstumme/code/personal/fastify-sample/node_modules/avvio/plugin.js:267:10)
    at Task.release (/Users/danielstumme/code/personal/fastify-sample/node_modules/fastq/queue.js:149:16)
    at worked (/Users/danielstumme/code/personal/fastify-sample/node_modules/fastq/queue.js:201:10)
    at /Users/danielstumme/code/personal/fastify-sample/node_modules/avvio/plugin.js:270:7
    at done (/Users/danielstumme/code/personal/fastify-sample/node_modules/avvio/plugin.js:202:5)
    at check (/Users/danielstumme/code/personal/fastify-sample/node_modules/avvio/plugin.js:226:9)
(node:82178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:82178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Discovered issue while trying to use Apollo's `@contact` directive: https://www.apollographql.com/docs/studio/federated-graphs/#adding-the-contact-directive-to-your-subgraph) which requires the schema object to be specified as it's a directive on the schema object.

From my initial investigate this is caused by the following [line](https://github.com/mercurius-js/mercurius/blob/master/lib/federation.js#L95) as the schema definition object doesn't have a name property set. 

Console log of schemaDefinitions from the getStubTypes func:

```
[
  {
    kind: 'ObjectTypeDefinition',
    description: undefined,
    name: { kind: 'Name', value: 'Book', loc: [Object] },
    interfaces: [],
    directives: [],
    fields: [ [Object], [Object] ],
    loc: { start: 0, end: 44 }
  },
  {
    kind: 'ObjectTypeDefinition',
    description: undefined,
    name: { kind: 'Name', value: 'Query', loc: [Object] },
    interfaces: [],
    directives: [],
    fields: [ [Object] ],
    loc: { start: 77, end: 106 }
  },
  {
    kind: 'SchemaDefinition',
    description: undefined,
    directives: [],
    operationTypes: [ [Object] ],
    loc: { start: 108, end: 132 }
  }
]
```

Running on macos: 10.15.7
node version: v12.18.4

**Comment by mcollina** [comment]
Can you take a look if https://github.com/mercurius-js/mercurius/pull/581 solves your problem?

**Comment by destumme** [comment]
It does indeed, thanks for taking a look so quickly. And as always, thanks for everything you do for the community.
