### ISSUE TITLE
Subscriptions: TypeError: Cannot set property 'close' of undefined

### ISSUE THREAD

**Issue by artmarydotir** [mercurius-js/mercurius#772]
nodejs version: v16.7.0
os version: nodejs official docker image debian 11.2
fastify version: 3.20
mercurius : 8.12.2
mqemitter-redis": 4.1.0
ioredis: 4.0.0

*******

Hi, im using [Subscription support (with redis)], but getting this error at subscribing. im not implemented the publish yet , bcuz at first i can not subscribe.

```
type Subscription {
  SubSetting: String
}

```

```
module.exports = async (_, __, { pubsub }) => {
  // console.log(pubsub);
  pubsub
    .subscribe('NOTIFICATION_ADDED')
    .then((a) => {
      console.log(a);
    })
    .catch((e) => {
      console.log(e);
    });
};
```
**the pubsub object console log result:**
```

PubSub {
  emitter: MQEmitterRedis {
    _opts: {
      port: 6379,
      host: 'htm-redis',
      username: undefined,
      password: undefined,
      db: 2,
      keyPrefix: 'htm-test:mqe:',
      matchEmptyLevels: true,
      separator: '/',
      wildcardOne: '+',
      wildcardSome: '#',
      regexWildcardOne: /\+/g,
      regexWildcardSome: /\/?#/g
    },
   , ..........
   ...........
```

And the error im getting:
```
TypeError: Cannot set property 'close' of undefined
    at /app/api/node_modules/mercurius/lib/subscriber.js:28:19
    at new Promise (<anonymous>)
    at PubSub.subscribe (/app/api/node_modules/mercurius/lib/subscriber.js:11:12)
    at Object.module.exports [as SubSetting] (/app/api/src/GraphQL/Subscribe/SubSetting.js:17:6)
    at resolveField (/app/api/node_modules/graphql/execution/execute.js:464:18)
    at executeFields (/app/api/node_modules/graphql/execution/execute.js:292:18)
    at executeOperation (/app/api/node_modules/graphql/execution/execute.js:236:122)
    at executeImpl (/app/api/node_modules/graphql/execution/execute.js:116:14)
    at execute (/app/api/node_modules/graphql/execution/execute.js:60:63)
    at Object.fastifyGraphQl [as graphql] (/app/api/node_modules/mercurius/index.js:569:29)
```

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by artmarydotir** [comment]
> Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

ِYes, I understand. I thought to myself, maybe this is a common mistake.
this problem is currently running on a project that I can not publish.
but thank you for your answer and in the next few days I will publish a small repository of my problem again. 🌷
