### ISSUE TITLE
Error is logged with `disableRequestLogging` and `logger`

### ISSUE THREAD

**Issue by ZiiMakc** [mercurius-js/mercurius#782]
I would like to log errors manually and don't log know handled errors like "Nickname is taken".

With configuration like this:
```
const app = fastify({ logger: pino(options, stream), disableRequestLogging: true });
``` 

When error is thrown from resolver it's logged in info level:
```
[01:01:43.968] INFO: Nickname is taken {"reqId":"req-1"}
    err: {
      "type": "GraphQLError",
      "message": "Nickname is taken",
      "stack":
          Error: Nickname is taken
              at Function.checkUniqueNickname (packages/api/build/services/user.js:264:19)
              at async Function.update (packages/api/build/services/user.js:187:17)
              at async Object.fastifyGraphQl [as graphql] node_modules\.pnpm\mercurius@9.3.6\node_modules\mercurius\index.js:627:23)
      "path": [
        "userUpdate"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {
        "isCustomErr": true,
      }
    }
```

With `logger` set to `false` log messages are gone, but also `req.log.error` will not work.
```
const app = fastify({ logger: false, disableRequestLogging: true });
``` 

# Expected behavior: 

Error thrown from resolver should not be logged if `disableRequestLogging` is `true`.

---
Additional information:

Logger options:
```
const options: LoggerOptions = {
  level: logLevel,
  base: null,
  serializers: {
    err: pinoStdSerializers.err,
    error: pinoStdSerializers.err,
    req: pinoStdSerializers.req,
    res: pinoStdSerializers.res,
  },
};

const stream: DestinationStream = isDev
  ? pinoPretty({
      translateTime: 'SYS:HH:MM:ss.l',
      singleLine: true,
      ignore: 'req.headers,req.id,req.remoteAddress,req.remotePort,res.headers',
    })
  : process.stdout;
```

**Comment by mcollina** [comment]
disableRequestLogger disables all the logging of Fastify, not mercurius. Currently there is no such option for Mercurius, would you like to add one?

**Comment by ZiiMakc** [comment]
Got it, maybe I will do it later, will close for now.
