### ISSUE TITLE
Cannot read properties of undefined (reading 'entityResolversFactory')

### ISSUE THREAD

**Issue by andreysoktoev** [mercurius-js/mercurius#834]
Cannot get **QUERY** response data via WebSocket in Gateway mode.

Gateway error:
```js
{
  "level":30,
  "time":1659499854014,
  "pid":7278,
  "hostname":"carbon",
  "err":{"type":"GraphQLError",
  "message":"Cannot read properties of undefined (reading 'entityResolversFactory')",
  "stack":"TypeError: Cannot read properties of undefined (reading 'entityResolversFactory')\n
    at /home/asktv/graphql-ws-gateway/node_modules/mercurius/lib/gateway/make-resolver.js:482:35\n
    at executeField (/home/asktv/graphql-ws-gateway/node_modules/graphql/execution/execute.js:481:20)\n
    at executeFields (/home/asktv/graphql-ws-gateway/node_modules/graphql/execution/execute.js:413:20)\n
    at executeOperation (/home/asktv/graphql-ws-gateway/node_modules/graphql/execution/execute.js:344:14)\n
    at execute (/home/asktv/graphql-ws-gateway/node_modules/graphql/execution/execute.js:136:20)\n
    at Object.fastifyGraphQl [as graphql] (/home/asktv/graphql-ws-gateway/node_modules/mercurius/index.js:650:29)\n
    at SubscriptionConnection._executeQueryOrMutation (/home/asktv/graphql-ws-gateway/node_modules/mercurius/lib/subscription-connection.js:277:41)\n
    at SubscriptionConnection.handleGQLStart (/home/asktv/graphql-ws-gateway/node_modules/mercurius/lib/subscription-connection.js:193:18)\n
    at SubscriptionConnection.handleMessage (/home/asktv/graphql-ws-gateway/node_modules/mercurius/lib/subscription-connection.js:77:16)\n
    at SubscriptionConnection.handleConnection (/home/asktv/graphql-ws-gateway/node_modules/mercurius/lib/subscription-connection.js:50:20)",
  "path":["one"],
  "locations":[{"line":1,3}],
  "extensions":{}},
  "msg":"Cannot read properties of undefined (reading 'entityResolversFactory')"
}
```
Client error:
```js
{
  errors: [
    {
      message: "Cannot read properties of undefined (reading 'entityResolversFactory')",
      locations: [Array],
      path: [Array]
    }
  ],
  data: { one: null }
}
```
Gateway:
```js
import fastify from 'fastify'
import mercurius from 'mercurius'

export default () => {
  const f = fastify({ logger: true })

  f.register(mercurius, {
    subscription: {
      fullWsTransport: true
    },
    gateway: {
      services: [
        {
          name: 'one',
          url: 'http://localhost:3001/graphql',
          wsUrl: 'ws://localhost:3001/graphql',
        },
        {
          name: 'two',
          url: 'http://localhost:3002/graphql',
          wsUrl: 'ws://localhost:3002/graphql'
        }
      ]
    }
  })

  return f
}
```
Service:
```js
import fastify from 'fastify'
import mercurius from 'mercurius'

const schema = `
  extend type Query {
    one: Int
  }
`

const resolvers = {
  Query: {
    one: async () => 1
  }
}

export default () => {
  const f = fastify({ logger: true })

  f.register(mercurius, {
    schema,
    resolvers,
    subscription: {
      fullWsTransport: true
    },
    federationMetadata: true
  })

  return f
}
```
Client:
```js
import { createClient } from 'graphql-ws'
import ws from 'ws'

const client = createClient({
  url: 'ws://localhost:3000/graphql',
  webSocketImpl: ws,
})

async function start() {
  const result = await new Promise((resolve, reject) => {
    let result
    client.subscribe(
      {
        query: `{ one }`
      },
      {
        next: (data) => (result = data),
        error: reject,
        complete: () => resolve(result),
      },
    )
  })

  console.log(result)
}

start()
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by andreysoktoev** [comment]
Actually, i don't have enough expertise to find out the solution. Maybe someone more experienced can help?
