### ISSUE TITLE
NestJs, Mercurius Federation throws GraphQLError: Syntax Error: Unexpected "@".

### ISSUE THREAD

**Issue by sushilkjaiswar** [mercurius-js/mercurius#867]
Nestjs + Mercurius + Federation Graphql API server when setup is throwing following error,

 ```
return new _GraphQLError.GraphQLError(`Syntax Error: ${description}`, {
         ^
GraphQLError: Syntax Error: Unexpected "@".
    at syntaxError (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/language/parser.js:1458:41)
    at Parser.parseDefinition (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/language/parser.js:212:16)
    at Parser.many (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/language/parser.js:1511:26)
    at Parser.parseDocument (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/language/parser.js:122:25)
    at parse (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/graphql/language/parser.js:32:17)
    at buildFederationSchema (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/mercurius/lib/federation.js:279:32)
    at buildGateway (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/mercurius/lib/gateway.js:316:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fp.name (/Users/sushilkumarjaiswar/workspace/work/nodeapp/fedapp/gateway/node_modules/mercurius/index.js:237:15)
```
Below is the important piece of code and schema I used from NestJS federation example combined with Mercurius example. I have read similar issues faced by other developers but in their case error reported was different than what is shown in my codebase. I heard Mercurius also has @extends directive but not clear instruction on how to use for federation applications. Any tip or guidance would be helpful and thanks in advance.
 
user.graphql
```
extend type Query {
  getUser(id: ID!): User
}

type User @key(fields: "id") {
  id: ID!
  name: String!
}

```
user.module.ts
```
import {
  MercuriusFederationDriver,
  MercuriusFederationDriverConfig,
} from '@nestjs/mercurius';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { UsersResolver } from './users.resolver';
import { UsersService } from './users.service';

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusFederationDriverConfig>({
      driver: MercuriusFederationDriver,
      typePaths: ['**/*.graphql'],
    }),
  ],
  providers: [UsersService, UsersResolver],
})
export class UsersModule {}

```

post.graphql

```
extend type Query {
  getPosts: [Post]
}

type Post @key(fields: "id") {
  id: ID!
  title: String
  content: String
}

```
posts.modeule.ts
```
import {
  MercuriusFederationDriver,
  MercuriusFederationDriverConfig,
} from '@nestjs/mercurius';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { PostsResolver } from './posts.resolver';
import { UsersResolver } from './users.resolver';

import { PostsService } from './posts.service';

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusFederationDriverConfig>({
      driver: MercuriusFederationDriver,
      typePaths: ['**/*.graphql'],
    }),
  ],
  providers: [PostsService, PostsResolver],
})
export class PostsModule {}

```

gateway.module.ts

```
import {
  MercuriusGatewayDriver,
  MercuriusGatewayDriverConfig,
} from '@nestjs/mercurius';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusGatewayDriverConfig>({
      graphiql: true,
      driver: MercuriusGatewayDriver,
      gateway: {
        services: [
          { name: 'users', url: 'http://localhost:3002/graphql' },
          { name: 'posts', url: 'http://localhost:3001/graphql' },
        ],
      },
    }),
  ],
})
export class AppModule {}
```

Versions of the libraries used 

```
    "@apollo/subgraph": "^2.1.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.1.1",
    "@nestjs/mercurius": "^10.1.0",
    "@nestjs/platform-fastify": "^9.0.11",
    "graphql": "^16.6.0",
    "mercurius": "^11.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
```

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

**Comment by sushilkjaiswar** [comment]
Thanks for the prompt @mcollina. I thought my issue was oriented towards Mercurius than NestJS but anyways I will try to discuss on discord channel. Thank you for referring discord channel.

**Comment by mcollina** [comment]
I'll be happy to help if you can create a simple repro just using Mercuruius.
